services:
  digibyte-ckpool:
    build:
      context: ckpool/
      # For x86_64 builds:
      args:
        TARGETARCH: amd64
      # Or for ARM64:
      # args:
      #   TARGETARCH: arm64
    container_name: digibyte-ckpool
    # Restart the container automatically if it exits:
    restart: always
    # Define environment variables to fill the config files at runtime:
    healthcheck:
      test: ["CMD", "bash", "/healthcheck.sh"]
      interval: 10s
      timeout: 30s
      retries: 10
      start_period: 60s
    environment:
      # DigiByte config
      TESTNET: "0"
      ALGO: "sha256d"
      DAEMON: "1"
      SERVER: "1"
      TXINDEX: "0"
      MAXCONNECTIONS: "300"
      DISABLEWALLET: "0"
      RPCALLOWIP: "0.0.0.0/0"
      PORT: "8433"
      RPCPORT: "8432"
      RPCBIND: "0.0.0.0"
      RPCUSER: "rpcuser"
      RPCPASSWORD: "rpcpassword"
      ONLYNET: "IPv4"
      ZMQPUBHASHBLOCK: "tcp://127.0.0.1:28435"
      DATADIR: "/home/cna.digibyte/mainnet"

      # ckpool config
      BTCD_URL: "127.0.0.1:8432"
      BTCD_AUTH: "rpcuser"
      BTCD_PASS: "rpcpassword"
      SERVERURL: "0.0.0.0:3333"
      BTCADDRESS: "xxx"
      BTCSIG: "/mined by me/"
      BLOCKPOLL: "50"
      DONATION: "0.0"
      NONCE1LENGTH: "4"
      NONCE2LENGTH: "8"
      UPDATE_INTERVAL: "5"
      VERSION_MASK: "1fffe000"
      MINDIFF: "512"
      STARTDIFF: "10000"
      LOGDIR: "/logs"
      ZMQBLOCK: "tcp://127.0.0.1:28435"

    volumes:
      - ./ckpool/data:/home/cna.digibyte/mainnet
      - ./ckpool/data/logs:/logs

    ports:
      # Publish DigiByte ports:
      - "8433:8433"  # p2p
      # Publish DigiByte RPC port:
      - "8432:8432"  # rpc
      # Publish ckpool port (if you want to accept external connections for miners):
      - "3333:3333"
      # API port (for ckstats):
      - "4028:4028"
      # API port (for ckstats):
      - "3001:80"

  db:
    image: postgres:13
    # Restart the container automatically if it exits:
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: ckstats
      POSTGRES_PASSWORD: ckstats
      POSTGRES_DB: ckstats
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ckstats -t 20 && psql -U ckstats -d dbshadow -c 'SELECT 1' >/dev/null 2>&1"]
      interval: 20s
      timeout: 30s
      retries: 5
  ckstats:
    build:
      context: ckstats/
      dockerfile: Dockerfile
      # For x86_64 builds:
      args:
        TARGETARCH: amd64
      # Or for ARM64:
      # args:
      #   TARGETARCH: arm64
    container_name: ckstats
    # Restart the container automatically if it exits:
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://ckstats:ckstats@db/ckstats"
      SHADOW_DATABASE_URL: "postgres://ckstats:ckstats@db/dbshadow"
      DB_HOST: "db"
      DB_USER: "ckstats"
      DB_PASSWORD: "ckstats"
      DB_NAME: "ckstats"
      DB_PORT: "5432"
      API_URL: "http://digibyte-ckpool:4028"
      RPCUSER: "rpcuser"
      RPCPASSWORD: "rpcpassword"
      RPCPORT: "8432"
    ports:
    # Publish ckstats port:
      - "3000:3000"



